title: Ziming Qiu # your name (or website title) here
logo: "/images/personal.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  4th Year PH.D. Student at NYU ECE. 
  <br><br>
  Research Interests: Computer Vision, Machine Learning and Image Analysis.  
  <br><br>
  <a href="https://www.linkedin.com/in/ziming-qiu-045642161/">LinkedIn Profile</a>
  <br><br>
  <a href="/pdf/ziming_qiu_cv.pdf">Resume</a>
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
